name: Second action

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['First action']
    types: [completed]

jobs:
  second:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Second action successfully finished!"
      - run: |
          echo "Triggered by: ${{ github.event_name }}"

          echo "result: ${{ github.event.workflow_run.conclusion }}"

          RUN_ID=${{ github.event.workflow_run.id }}
          log_prefix=$(date +"%Y%m%d%H%M%S")
          log_file_name=${log_prefix}_logs.zip

          # Download logs using GitHub API
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -L \
               "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/logs" \
               --output $log_file_name
          
          echo "upload $log_file_name to S3: "

          # unzip $log_file_name
          ls