name: Second action

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['First action']
    types: [completed]

jobs:
  second:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Second action successfully finished!"
      - run: |
          echo "Triggered by: ${{ github.event_name }}"

          RUN_ID=${{ github.event.workflow_run.id }}
          echo "Downloading artifact from Run ID: $RUN_ID"

          echo "result: ${{ github.event.workflow_run.conclusion }}"