name: Target Log Workflow

on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - run: echo "test workflow successfully finished!"