name: Target Log Workflow

on:
  workflow_dispatch:
    inputs:
      input_target:
        description: Environment to deploy my app
        required: true
        type: choice
        options:
          - dev
          - stg
          - prd

jobs:
  first:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - run: echo "test workflow successfully finished!"
